### ISSUE TITLE
Doesn't seem to obey the Default Command setting

### ISSUE THREAD

**Issue by jayjanssen** [square/goose-vscode#7]
Goose is available on my system via `sq goose session start`, and i've updated my extension settings for that, but I still get the error "command 'extension.sendToGoose' not found" when I try to "Ask Goose" in vscode

**Comment by michaelneale** [comment]
ah good catch @jayjanssen - yes I made some mistakes when the command changed, will get fix out shortly

**Comment by michaelneale** [comment]
fix in progress: https://github.com/square/goose-vscode/pull/8

**Comment by michaelneale** [comment]
fixed - should be in an update now.

**Comment by jayjanssen** [comment]
thanks!
